obstacles:
  - frame_id: "panda_link0"
    namespace: "obstcales"
    id: 1
    type: 1  # Cube
    action: 0
    pose:
      position:
        x: 0.5
        y: -0.2
        z: 0.2
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    scale:
      x: 0.2
      y: 0.2
      z: 0.2
    color:
      r: 1.0
      g: 0.0
      b: 0.0
      a: 1.0
    velocity:
      linear:
        x: 0.0
        y: 0.0
        z: 0.0
      angular:
        x: 0.0
        y: 0.0
        z: 0.0
    lifetime: 0.0

  - frame_id: "panda_link0"
    namespace: "obstcales"
    id: 2
    type: 3  # Cylinder
    action: 0
    pose:
      position:
        x: 0.0
        y: -0.4
        z: 0.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    scale:
      x: 0.2
      y: 0.2
      z: 0.2
    color:
      r: 0.0
      g: 1.0
      b: 0.0
      a: 1.0
    velocity:
      linear:
        x: 0.0
        y: 0.0
        z: 0.0
      angular:
        x: 0.0
        y: 0.0
        z: 0.0
    lifetime: 0.0

  - frame_id: "panda_link0"
    namespace: "obstcales"
    id: 3
    type: 2  # Sphere
    action: 0
    pose:
      position:
        x: 0.6
        y: 0.2
        z: 0.6
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    scale:
      x: 0.3
      y: 0.3
      z: 0.3        
    color:
      r: 0.0
      g: 0.0
      b: 1.0
      a: 1.0
    velocity:
      linear:
        x: 0.0
        y: 0.0
        z: 0.0
      angular:
        x: 0.0
        y: 0.0
        z: 0.0
    lifetime: 0.0
    
start_pose:
  position:
    x: 0.3
    y: -0.2
    z: 0.3
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

goal_pose:
  position:
    x: 0.3
    y: -0.2
    z: 0.3
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
